using UnityEngine;

public class DynamicHole : MonoBehaviour
{
    public Material holeMaterial; // Matťriau utilisant le shader
    public GameObject targetObject; // Objet crťant le trou
    public Transform holeSpriteTransform; // Transform du sprite trouť
    [HideInInspector]public float maskSize; // Taille du trou en unitťs mondiales
    [SerializeField] public float MaskSize;

    public GameObject FakePoint;
    private void Start()
    {
        maskSize = MaskSize;
    }

    void Update()
    {
        if (holeMaterial != null && targetObject != null && holeSpriteTransform != null)
        {
            Vector3 localPosition = holeSpriteTransform.InverseTransformPoint(targetObject.transform.position);

            Vector3 localScale = holeSpriteTransform.localScale;
            float adjustedMaskSize = maskSize / Mathf.Max(localScale.x, localScale.y);

            holeMaterial.SetVector("_MaskPosition", new Vector4(localPosition.x, localPosition.y, 0, 0));
            holeMaterial.SetFloat("_MaskSize", adjustedMaskSize);
        }
    }
}
